name = "goose-joke-generator-d1"
compatibility_date = "2024-11-11"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 7153

[[d1_databases]]
binding = "DB"
database_name = "goose-joke-generator-d1"
database_id = "63afac61-bc33-434d-b6f7-7ac3a6917fd1"
migrations_dir = "drizzle/migrations"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "GOOSE_JOKES_CACHE"
id = "0e612a8362a5410fbab299caf308e5ac"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

[ai]
binding = "AI"
